// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reorg.sql

package sqlc

import (
	"context"
	"database/sql"
)

const ClearReorgDependencyForeclosure = `-- name: ClearReorgDependencyForeclosure :exec
UPDATE reorg_dependencies
SET foreclosing_evidence = NULL,
    foreclosing_on_chain = FALSE
WHERE child_id = $1
  AND parent_id = $2
  AND foreclosing_act_certified = FALSE
`

type ClearReorgDependencyForeclosureParams struct {
	ChildID  int64
	ParentID int64
}

// A certified foreclosure is absorbing and never cleared.
func (q *Queries) ClearReorgDependencyForeclosure(ctx context.Context, arg ClearReorgDependencyForeclosureParams) error {
	_, err := q.db.ExecContext(ctx, ClearReorgDependencyForeclosure, arg.ChildID, arg.ParentID)
	return err
}

const CountLiveReorgDependents = `-- name: CountLiveReorgDependents :one
SELECT COUNT(*)
FROM reorg_dependencies d
JOIN reorg_anchorings child
  ON child.id = d.child_id
WHERE d.parent_id = $1
  AND child.phase_code < 3
`

func (q *Queries) CountLiveReorgDependents(ctx context.Context, parentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountLiveReorgDependents, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const FetchLiveReorgAnchoringsByWitness = `-- name: FetchLiveReorgAnchoringsByWitness :many
SELECT id, site_id, threshold, match_version, match_data, payload_version, payload_data, created_height, phase_code, phase_evidence, delivered_code, delivered_evidence, witness_txid, stuck, delivery_attempts, last_delivery_error, next_delivery_at, terminal_at
FROM reorg_anchorings
WHERE witness_txid = $1
  AND phase_code < 3
ORDER BY id
`

func (q *Queries) FetchLiveReorgAnchoringsByWitness(ctx context.Context, witnessTxid []byte) ([]ReorgAnchoring, error) {
	rows, err := q.db.QueryContext(ctx, FetchLiveReorgAnchoringsByWitness, witnessTxid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReorgAnchoring
	for rows.Next() {
		var i ReorgAnchoring
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Threshold,
			&i.MatchVersion,
			&i.MatchData,
			&i.PayloadVersion,
			&i.PayloadData,
			&i.CreatedHeight,
			&i.PhaseCode,
			&i.PhaseEvidence,
			&i.DeliveredCode,
			&i.DeliveredEvidence,
			&i.WitnessTxid,
			&i.Stuck,
			&i.DeliveryAttempts,
			&i.LastDeliveryError,
			&i.NextDeliveryAt,
			&i.TerminalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const FetchReorgAnchoring = `-- name: FetchReorgAnchoring :one
SELECT id, site_id, threshold, match_version, match_data, payload_version, payload_data, created_height, phase_code, phase_evidence, delivered_code, delivered_evidence, witness_txid, stuck, delivery_attempts, last_delivery_error, next_delivery_at, terminal_at
FROM reorg_anchorings
WHERE id = $1
`

func (q *Queries) FetchReorgAnchoring(ctx context.Context, id int64) (ReorgAnchoring, error) {
	row := q.db.QueryRowContext(ctx, FetchReorgAnchoring, id)
	var i ReorgAnchoring
	err := row.Scan(
		&i.ID,
		&i.SiteID,
		&i.Threshold,
		&i.MatchVersion,
		&i.MatchData,
		&i.PayloadVersion,
		&i.PayloadData,
		&i.CreatedHeight,
		&i.PhaseCode,
		&i.PhaseEvidence,
		&i.DeliveredCode,
		&i.DeliveredEvidence,
		&i.WitnessTxid,
		&i.Stuck,
		&i.DeliveryAttempts,
		&i.LastDeliveryError,
		&i.NextDeliveryAt,
		&i.TerminalAt,
	)
	return i, err
}

const FetchReorgCandidateSpends = `-- name: FetchReorgCandidateSpends :many
SELECT id, anchoring_id, spender_txid, raw_tx, verdict, on_chain, block_hash, block_height, tx_index, act_certified, block_header, merkle_proof, spent_outpoints
FROM reorg_candidate_spends
WHERE anchoring_id = $1
ORDER BY spender_txid
`

func (q *Queries) FetchReorgCandidateSpends(ctx context.Context, anchoringID int64) ([]ReorgCandidateSpend, error) {
	rows, err := q.db.QueryContext(ctx, FetchReorgCandidateSpends, anchoringID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReorgCandidateSpend
	for rows.Next() {
		var i ReorgCandidateSpend
		if err := rows.Scan(
			&i.ID,
			&i.AnchoringID,
			&i.SpenderTxid,
			&i.RawTx,
			&i.Verdict,
			&i.OnChain,
			&i.BlockHash,
			&i.BlockHeight,
			&i.TxIndex,
			&i.ActCertified,
			&i.BlockHeader,
			&i.MerkleProof,
			&i.SpentOutpoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const FetchReorgDependencyEdgesByChild = `-- name: FetchReorgDependencyEdgesByChild :many
SELECT id, child_id, parent_id, parent_witness_txid, foreclosing_evidence, foreclosing_on_chain, foreclosing_act_certified
FROM reorg_dependencies
WHERE child_id = $1
ORDER BY id
`

func (q *Queries) FetchReorgDependencyEdgesByChild(ctx context.Context, childID int64) ([]ReorgDependency, error) {
	rows, err := q.db.QueryContext(ctx, FetchReorgDependencyEdgesByChild, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReorgDependency
	for rows.Next() {
		var i ReorgDependency
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.ParentID,
			&i.ParentWitnessTxid,
			&i.ForeclosingEvidence,
			&i.ForeclosingOnChain,
			&i.ForeclosingActCertified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const FetchReorgDependencyEdgesByParent = `-- name: FetchReorgDependencyEdgesByParent :many
SELECT d.id, d.child_id, d.parent_id, d.parent_witness_txid, d.foreclosing_evidence, d.foreclosing_on_chain, d.foreclosing_act_certified
FROM reorg_dependencies d
JOIN reorg_anchorings child
  ON child.id = d.child_id
WHERE d.parent_id = $1
  AND child.phase_code < 3
ORDER BY d.id
`

func (q *Queries) FetchReorgDependencyEdgesByParent(ctx context.Context, parentID int64) ([]ReorgDependency, error) {
	rows, err := q.db.QueryContext(ctx, FetchReorgDependencyEdgesByParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReorgDependency
	for rows.Next() {
		var i ReorgDependency
		if err := rows.Scan(
			&i.ID,
			&i.ChildID,
			&i.ParentID,
			&i.ParentWitnessTxid,
			&i.ForeclosingEvidence,
			&i.ForeclosingOnChain,
			&i.ForeclosingActCertified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const FetchReorgTriggerOutpoints = `-- name: FetchReorgTriggerOutpoints :many
SELECT id, anchoring_id, outpoint_txid, outpoint_index, pk_script, height_hint
FROM reorg_trigger_outpoints
WHERE anchoring_id = $1
ORDER BY outpoint_txid, outpoint_index
`

func (q *Queries) FetchReorgTriggerOutpoints(ctx context.Context, anchoringID int64) ([]ReorgTriggerOutpoint, error) {
	rows, err := q.db.QueryContext(ctx, FetchReorgTriggerOutpoints, anchoringID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReorgTriggerOutpoint
	for rows.Next() {
		var i ReorgTriggerOutpoint
		if err := rows.Scan(
			&i.ID,
			&i.AnchoringID,
			&i.OutpointTxid,
			&i.OutpointIndex,
			&i.PkScript,
			&i.HeightHint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const InsertReorgAnchoring = `-- name: InsertReorgAnchoring :one

INSERT INTO reorg_anchorings (
    site_id, threshold, match_version, match_data, payload_version,
    payload_data, created_height, phase_code, phase_evidence,
    delivered_code, delivered_evidence, next_delivery_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, 0
)
RETURNING id
`

type InsertReorgAnchoringParams struct {
	SiteID            string
	Threshold         int32
	MatchVersion      int16
	MatchData         []byte
	PayloadVersion    int16
	PayloadData       []byte
	CreatedHeight     int32
	PhaseCode         int16
	PhaseEvidence     []byte
	DeliveredCode     int16
	DeliveredEvidence []byte
}

// Phase codes mirror tapreorg.PhaseCode: 0 unwitnessed, 1 witnessed,
// 2 conflicted, 3 buried, 4 abandoned, 5 withdrawn. Codes >= 3 are
// terminal; the literals below must stay in sync with that enum.
func (q *Queries) InsertReorgAnchoring(ctx context.Context, arg InsertReorgAnchoringParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, InsertReorgAnchoring,
		arg.SiteID,
		arg.Threshold,
		arg.MatchVersion,
		arg.MatchData,
		arg.PayloadVersion,
		arg.PayloadData,
		arg.CreatedHeight,
		arg.PhaseCode,
		arg.PhaseEvidence,
		arg.DeliveredCode,
		arg.DeliveredEvidence,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const InsertReorgDependency = `-- name: InsertReorgDependency :exec
INSERT INTO reorg_dependencies (
    child_id, parent_id, parent_witness_txid
) VALUES (
    $1, $2, $3
)
`

type InsertReorgDependencyParams struct {
	ChildID           int64
	ParentID          int64
	ParentWitnessTxid []byte
}

func (q *Queries) InsertReorgDependency(ctx context.Context, arg InsertReorgDependencyParams) error {
	_, err := q.db.ExecContext(ctx, InsertReorgDependency, arg.ChildID, arg.ParentID, arg.ParentWitnessTxid)
	return err
}

const InsertReorgEffect = `-- name: InsertReorgEffect :one
INSERT INTO reorg_outbox (
    anchoring_id, effect_kind, payload_version, payload_data,
    created_at, next_attempt_at
) VALUES (
    $1, $2, $3, $4,
    $5, 0
)
RETURNING id
`

type InsertReorgEffectParams struct {
	AnchoringID    sql.NullInt64
	EffectKind     string
	PayloadVersion int16
	PayloadData    []byte
	CreatedAt      int64
}

func (q *Queries) InsertReorgEffect(ctx context.Context, arg InsertReorgEffectParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, InsertReorgEffect,
		arg.AnchoringID,
		arg.EffectKind,
		arg.PayloadVersion,
		arg.PayloadData,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const InsertReorgTriggerOutpoint = `-- name: InsertReorgTriggerOutpoint :exec
INSERT INTO reorg_trigger_outpoints (
    anchoring_id, outpoint_txid, outpoint_index, pk_script, height_hint
) VALUES (
    $1, $2, $3, $4,
    $5
)
`

type InsertReorgTriggerOutpointParams struct {
	AnchoringID   int64
	OutpointTxid  []byte
	OutpointIndex int32
	PkScript      []byte
	HeightHint    int32
}

func (q *Queries) InsertReorgTriggerOutpoint(ctx context.Context, arg InsertReorgTriggerOutpointParams) error {
	_, err := q.db.ExecContext(ctx, InsertReorgTriggerOutpoint,
		arg.AnchoringID,
		arg.OutpointTxid,
		arg.OutpointIndex,
		arg.PkScript,
		arg.HeightHint,
	)
	return err
}

const ListLiveReorgAnchorings = `-- name: ListLiveReorgAnchorings :many
SELECT id, site_id, threshold, match_version, match_data, payload_version, payload_data, created_height, phase_code, phase_evidence, delivered_code, delivered_evidence, witness_txid, stuck, delivery_attempts, last_delivery_error, next_delivery_at, terminal_at
FROM reorg_anchorings
WHERE phase_code < 3
ORDER BY id
`

func (q *Queries) ListLiveReorgAnchorings(ctx context.Context) ([]ReorgAnchoring, error) {
	rows, err := q.db.QueryContext(ctx, ListLiveReorgAnchorings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReorgAnchoring
	for rows.Next() {
		var i ReorgAnchoring
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Threshold,
			&i.MatchVersion,
			&i.MatchData,
			&i.PayloadVersion,
			&i.PayloadData,
			&i.CreatedHeight,
			&i.PhaseCode,
			&i.PhaseEvidence,
			&i.DeliveredCode,
			&i.DeliveredEvidence,
			&i.WitnessTxid,
			&i.Stuck,
			&i.DeliveryAttempts,
			&i.LastDeliveryError,
			&i.NextDeliveryAt,
			&i.TerminalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListReorgAnchorings = `-- name: ListReorgAnchorings :many
SELECT id, site_id, threshold, match_version, match_data, payload_version, payload_data, created_height, phase_code, phase_evidence, delivered_code, delivered_evidence, witness_txid, stuck, delivery_attempts, last_delivery_error, next_delivery_at, terminal_at
FROM reorg_anchorings
ORDER BY id
`

func (q *Queries) ListReorgAnchorings(ctx context.Context) ([]ReorgAnchoring, error) {
	rows, err := q.db.QueryContext(ctx, ListReorgAnchorings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReorgAnchoring
	for rows.Next() {
		var i ReorgAnchoring
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Threshold,
			&i.MatchVersion,
			&i.MatchData,
			&i.PayloadVersion,
			&i.PayloadData,
			&i.CreatedHeight,
			&i.PhaseCode,
			&i.PhaseEvidence,
			&i.DeliveredCode,
			&i.DeliveredEvidence,
			&i.WitnessTxid,
			&i.Stuck,
			&i.DeliveryAttempts,
			&i.LastDeliveryError,
			&i.NextDeliveryAt,
			&i.TerminalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListReorgPendingDeliveries = `-- name: ListReorgPendingDeliveries :many
SELECT id, site_id, threshold, match_version, match_data, payload_version, payload_data, created_height, phase_code, phase_evidence, delivered_code, delivered_evidence, witness_txid, stuck, delivery_attempts, last_delivery_error, next_delivery_at, terminal_at
FROM reorg_anchorings
WHERE (phase_code != delivered_code
       OR phase_evidence != delivered_evidence)
  AND next_delivery_at <= $1
ORDER BY id
`

func (q *Queries) ListReorgPendingDeliveries(ctx context.Context, now int64) ([]ReorgAnchoring, error) {
	rows, err := q.db.QueryContext(ctx, ListReorgPendingDeliveries, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReorgAnchoring
	for rows.Next() {
		var i ReorgAnchoring
		if err := rows.Scan(
			&i.ID,
			&i.SiteID,
			&i.Threshold,
			&i.MatchVersion,
			&i.MatchData,
			&i.PayloadVersion,
			&i.PayloadData,
			&i.CreatedHeight,
			&i.PhaseCode,
			&i.PhaseEvidence,
			&i.DeliveredCode,
			&i.DeliveredEvidence,
			&i.WitnessTxid,
			&i.Stuck,
			&i.DeliveryAttempts,
			&i.LastDeliveryError,
			&i.NextDeliveryAt,
			&i.TerminalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ListReorgPendingEffects = `-- name: ListReorgPendingEffects :many
SELECT id, anchoring_id, effect_kind, payload_version, payload_data, created_at, attempts, last_error, next_attempt_at, dispatched_at
FROM reorg_outbox
WHERE dispatched_at IS NULL
  AND next_attempt_at <= $1
ORDER BY id
LIMIT $2
`

type ListReorgPendingEffectsParams struct {
	Now        int64
	MaxEffects int32
}

func (q *Queries) ListReorgPendingEffects(ctx context.Context, arg ListReorgPendingEffectsParams) ([]ReorgOutbox, error) {
	rows, err := q.db.QueryContext(ctx, ListReorgPendingEffects, arg.Now, arg.MaxEffects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReorgOutbox
	for rows.Next() {
		var i ReorgOutbox
		if err := rows.Scan(
			&i.ID,
			&i.AnchoringID,
			&i.EffectKind,
			&i.PayloadVersion,
			&i.PayloadData,
			&i.CreatedAt,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
			&i.DispatchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MarkReorgAnchoringDelivered = `-- name: MarkReorgAnchoringDelivered :exec
UPDATE reorg_anchorings
SET delivered_code = $1,
    delivered_evidence = $2,
    stuck = FALSE,
    delivery_attempts = 0,
    last_delivery_error = NULL,
    next_delivery_at = 0,
    terminal_at = $3
WHERE id = $4
`

type MarkReorgAnchoringDeliveredParams struct {
	DeliveredCode     int16
	DeliveredEvidence []byte
	TerminalAt        sql.NullInt64
	ID                int64
}

func (q *Queries) MarkReorgAnchoringDelivered(ctx context.Context, arg MarkReorgAnchoringDeliveredParams) error {
	_, err := q.db.ExecContext(ctx, MarkReorgAnchoringDelivered,
		arg.DeliveredCode,
		arg.DeliveredEvidence,
		arg.TerminalAt,
		arg.ID,
	)
	return err
}

const MarkReorgEffectDispatched = `-- name: MarkReorgEffectDispatched :exec
UPDATE reorg_outbox
SET dispatched_at = $1
WHERE id = $2
`

type MarkReorgEffectDispatchedParams struct {
	DispatchedAt sql.NullInt64
	ID           int64
}

func (q *Queries) MarkReorgEffectDispatched(ctx context.Context, arg MarkReorgEffectDispatchedParams) error {
	_, err := q.db.ExecContext(ctx, MarkReorgEffectDispatched, arg.DispatchedAt, arg.ID)
	return err
}

const RecordReorgDeliveryFailure = `-- name: RecordReorgDeliveryFailure :exec
UPDATE reorg_anchorings
SET delivery_attempts = delivery_attempts + 1,
    last_delivery_error = $1,
    next_delivery_at = $2,
    stuck = $3
WHERE id = $4
`

type RecordReorgDeliveryFailureParams struct {
	LastDeliveryError sql.NullString
	NextDeliveryAt    int64
	Stuck             bool
	ID                int64
}

func (q *Queries) RecordReorgDeliveryFailure(ctx context.Context, arg RecordReorgDeliveryFailureParams) error {
	_, err := q.db.ExecContext(ctx, RecordReorgDeliveryFailure,
		arg.LastDeliveryError,
		arg.NextDeliveryAt,
		arg.Stuck,
		arg.ID,
	)
	return err
}

const RecordReorgEffectFailure = `-- name: RecordReorgEffectFailure :exec
UPDATE reorg_outbox
SET attempts = attempts + 1,
    last_error = $1,
    next_attempt_at = $2
WHERE id = $3
`

type RecordReorgEffectFailureParams struct {
	LastError     sql.NullString
	NextAttemptAt int64
	ID            int64
}

func (q *Queries) RecordReorgEffectFailure(ctx context.Context, arg RecordReorgEffectFailureParams) error {
	_, err := q.db.ExecContext(ctx, RecordReorgEffectFailure, arg.LastError, arg.NextAttemptAt, arg.ID)
	return err
}

const SetReorgAnchoringPhase = `-- name: SetReorgAnchoringPhase :exec
UPDATE reorg_anchorings
SET phase_code = $1,
    phase_evidence = $2,
    witness_txid = $3,
    delivery_attempts = 0,
    stuck = FALSE,
    last_delivery_error = NULL,
    next_delivery_at = 0
WHERE id = $4
`

type SetReorgAnchoringPhaseParams struct {
	PhaseCode     int16
	PhaseEvidence []byte
	WitnessTxid   []byte
	ID            int64
}

// A newly sensed phase is a new delivery objective, so the failure
// bookkeeping of the previous objective (backoff, attempts, stuck)
// resets with it; a systematically failing handler re-sticks after
// the usual number of attempts.
func (q *Queries) SetReorgAnchoringPhase(ctx context.Context, arg SetReorgAnchoringPhaseParams) error {
	_, err := q.db.ExecContext(ctx, SetReorgAnchoringPhase,
		arg.PhaseCode,
		arg.PhaseEvidence,
		arg.WitnessTxid,
		arg.ID,
	)
	return err
}

const UpdateReorgDependencyForeclosure = `-- name: UpdateReorgDependencyForeclosure :exec
UPDATE reorg_dependencies
SET foreclosing_evidence = $1,
    foreclosing_on_chain = $2,
    foreclosing_act_certified = foreclosing_act_certified
        OR $3
WHERE child_id = $4
  AND parent_id = $5
`

type UpdateReorgDependencyForeclosureParams struct {
	ForeclosingEvidence     []byte
	ForeclosingOnChain      bool
	ForeclosingActCertified bool
	ChildID                 int64
	ParentID                int64
}

// Certification is sticky, as for candidate spends.
func (q *Queries) UpdateReorgDependencyForeclosure(ctx context.Context, arg UpdateReorgDependencyForeclosureParams) error {
	_, err := q.db.ExecContext(ctx, UpdateReorgDependencyForeclosure,
		arg.ForeclosingEvidence,
		arg.ForeclosingOnChain,
		arg.ForeclosingActCertified,
		arg.ChildID,
		arg.ParentID,
	)
	return err
}

const UpsertReorgCandidateSpend = `-- name: UpsertReorgCandidateSpend :exec
INSERT INTO reorg_candidate_spends (
    anchoring_id, spender_txid, raw_tx, verdict, on_chain, block_hash,
    block_height, tx_index, act_certified, block_header, merkle_proof,
    spent_outpoints
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12
)
ON CONFLICT (anchoring_id, spender_txid)
DO UPDATE SET
    raw_tx = EXCLUDED.raw_tx,
    verdict = EXCLUDED.verdict,
    on_chain = EXCLUDED.on_chain,
    block_hash = EXCLUDED.block_hash,
    block_height = EXCLUDED.block_height,
    tx_index = EXCLUDED.tx_index,
    act_certified = reorg_candidate_spends.act_certified
        OR EXCLUDED.act_certified,
    block_header = EXCLUDED.block_header,
    merkle_proof = EXCLUDED.merkle_proof,
    spent_outpoints = EXCLUDED.spent_outpoints
`

type UpsertReorgCandidateSpendParams struct {
	AnchoringID    int64
	SpenderTxid    []byte
	RawTx          []byte
	Verdict        sql.NullInt16
	OnChain        bool
	BlockHash      []byte
	BlockHeight    sql.NullInt32
	TxIndex        sql.NullInt32
	ActCertified   bool
	BlockHeader    []byte
	MerkleProof    []byte
	SpentOutpoints []byte
}

// Certification is sticky: once set it survives every later update,
// since a certified act crossing is never retracted by re-orgs.
func (q *Queries) UpsertReorgCandidateSpend(ctx context.Context, arg UpsertReorgCandidateSpendParams) error {
	_, err := q.db.ExecContext(ctx, UpsertReorgCandidateSpend,
		arg.AnchoringID,
		arg.SpenderTxid,
		arg.RawTx,
		arg.Verdict,
		arg.OnChain,
		arg.BlockHash,
		arg.BlockHeight,
		arg.TxIndex,
		arg.ActCertified,
		arg.BlockHeader,
		arg.MerkleProof,
		arg.SpentOutpoints,
	)
	return err
}
